### ISSUE TITLE
Ride Sharing: selecting departure address

### ISSUE THREAD

**Issue by landongerrits** [CruCentralCoast/iOS-App-iCrew#2]
When selecting departure address, there is an option to find your current location (icon in the lower right hand corner)

This button only location your current GPS location, it does not add any information about the user's actual address.

This button should autofill the search address field.

It may be more clear to the user to have some visual notification that their address has been added to the departure field.

**Comment by fedorareis** [comment]
Development has been moved to CruCentralCoast/CruiOS
